default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: englishpl_2022_development

test:
  <<: *default
  database: englishpl_2022_development


production:
  <<: *default
  database: englishpl_2022_development
  username:
  password:
